version: 6.3.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
skip_commits:
  files:
    - .github/
    - '**/*.md'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: dotnet tool install -g InheritDocTool
build_script: 
- cmd: echo __BUILD__
- dotnet restore src/ConfigCatClient.sln
- dotnet build -c %configuration% src/ConfigCatClient.sln 
after_build:
- cmd: echo __PACK__
- inheritdoc -o
- dotnet pack -c %configuration% /p:IncludeSymbols=true /p:PackageOutputPath=..\..\artifacts /p:SymbolPackageFormat=snupkg src\ConfigCatClient\ConfigCatClient.csproj
test_script:
- dotnet test src\ConfigCat.Client.Tests\ConfigCat.Client.Tests.csproj -f net45 -c %configuration% --no-build
- dotnet test src\ConfigCat.Client.Tests\ConfigCat.Client.Tests.csproj -f netcoreapp3.1 -c %configuration% --no-build
- dotnet test src\ConfigCat.Client.Tests\ConfigCat.Client.Tests.csproj -f net5.0 -c %configuration% --no-build
- dotnet test src\ConfigCat.Client.Tests\ConfigCat.Client.Tests.csproj -f net6.0 -c %configuration% --no-build
artifacts:
- path: artifacts\ConfigCat.Client.*.*nupkg
  name: NuGet 
notifications:
- provider: Email
  to:
  - developer@configcat.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
