version: 6.3.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script: 
 - cmd: echo __BUILD__
 - msbuild /verbosity:normal /t:Restore src/ConfigCatClient.sln
 - msbuild /verbosity:normal /t:Build src/ConfigCatClient.sln 
after_build:
 - cmd: echo __PACK__
 - msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%configuration% /p:PackageOutputPath=..\..\artifacts /p:SymbolPackageFormat=snupkg src\ConfigCatClient\ConfigCatClient.csproj
test_script:
- dotnet test test\stashbox.tests.csproj -f net45 -c %configuration% --no-build
- dotnet test test\stashbox.tests.csproj -f netcoreapp3.1 -c %configuration% --no-build
- dotnet test test\stashbox.tests.csproj -f net5.0 -c %configuration% --no-build
- dotnet test test\stashbox.tests.csproj -f net6.0 -c %configuration% --no-build
artifacts:
- path: artifacts\ConfigCat.Client.*.*nupkg
  name: NuGet 
notifications:
- provider: Email
  to:
  - developer@configcat.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
