version: 2.5.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
 - cmd: nuget.exe restore src/ConfigCatClient.sln
build:
  project: src/ConfigCatClient.sln
  verbosity: normal
after_build:
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%configuration% /p:PackageOutputPath=..\..\artifacts src\ConfigCatClient\ConfigCatClient.csproj
before_test:
 - ps: choco install opencover.portable --no-progress
 - ps: choco install codecov --no-progress
test_script:
 - ps: . .\set-debug-type.ps1 src\ConfigCatClient\ConfigCatClient.csproj
 - OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test src\ConfigCat.Client.Tests\ConfigCat.Client.Tests.csproj -c Release" -output:.\coverage.xml -filter:"+[*]ConfigCat.Client.* -[ConfigCatClientTests]*" -oldstyle -returntargetcode
after_test:
 - codecov -f "coverage.xml"
artifacts:
- path: artifacts\ConfigCat.Client.*.nupkg
  name: NuGet
notifications:
- provider: Email
  to:
  - developer@configcat.com
  on_build_success: false
  on_build_failure: true
